### ISSUE TITLE
v2.4.5 throwing NoClassDefFoundError whilst executing task with Spigot 1.12.1

### ISSUE THREAD

**Issue by martijn-heil** [DerPavlov/Cannons#15]
Cannons v2.4.5 is throwing an exception executing a task, with Spigot 1.12.1 (exact version down below). 

Stack trace:
```
[14:29:23 WARN]: [Cannons] Plugin Cannons v2.4.5 generated an exception while executing task 41
java.lang.NoClassDefFoundError: com/avaje/ebean/config/dbplatform/DatabasePlatform
        at at.pavlov.cannons.Cannons.initializeDatabase(Cannons.java:218) ~[?:?]
        at at.pavlov.cannons.Cannons.access$000(Cannons.java:46) ~[?:?]
        at at.pavlov.cannons.Cannons$1.run(Cannons.java:148) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar:git-Spigot-5340a52-27b8bf9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.1.jar:git-Spigot-5340a52-27b8bf9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.config.dbplatform.DatabasePlatform
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.1.jar:git-Spigot-5340a52-27b8bf9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.1.jar:git-Spigot-5340a52-27b8bf9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 8 more
```

Exact Spigot version:  CraftBukkit version git-Spigot-5340a52-27b8bf9 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by martijn-heil** [comment]
I see now you appear to have it fixed in v2.4.6 R0.4 SNAPSHOT, my bad, Clicked the download button at the Bukkit page which downloads the latest release, and v2.4.6 R0.4 SNAPSHOT is only beta yet, so that doesn't get downloaded.

**Comment by DerPavlov** [comment]
There are still minor problems with the MySQL implementation, but I plan to release the version soon.

**Comment by martijn-heil** [comment]
Ah okay, thanks
