### ISSUE TITLE
Cannons is throwing an error

### ISSUE THREAD

**Issue by JustinDevB** [DerPavlov/Cannons#43]
[07:38:52 ERROR]: Could not pass event EntityDamageByEntityEvent to Cannons v2.5.10
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.BlockFace.getOppositeFace()" because "this.mainFace" is null
        at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:139) ~[patched_1.16.5.jar:git-Purpur-1056]
        at at.pavlov.cannons.utils.CannonsUtil.findSurface(CannonsUtil.java:655) ~[?:?]
        at at.pavlov.cannons.CreateExplosion.blockBreaker(CreateExplosion.java:157) ~[?:?]
        at at.pavlov.cannons.CreateExplosion.detonate(CreateExplosion.java:809) ~[?:?]
        at at.pavlov.cannons.CreateExplosion.directHit(CreateExplosion.java:790) ~[?:?]
        at at.pavlov.cannons.projectile.ProjectileManager.directHitProjectile(ProjectileManager.java:136) ~[?:?]
        at at.pavlov.cannons.listener.EntityListener.onProjectileHitEntity(EntityListener.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor221.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1056]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:949) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1136) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1126) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1122) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.EntityItem.damageEntity(EntityItem.java:321) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:224) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:1190) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:2453) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:1184) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.createExplosion(CraftWorld.java:1033) ~[patched_1.16.5.jar:git-Purpur-1056]
        at at.pavlov.cannons.CreateExplosion.detonate(CreateExplosion.java:876) ~[?:?]
        at at.pavlov.cannons.CreateExplosion.directHit(CreateExplosion.java:790) ~[?:?]
        at at.pavlov.cannons.projectile.ProjectileManager.directHitProjectile(ProjectileManager.java:136) ~[?:?]
        at at.pavlov.cannons.listener.EntityListener.onProjectileHitEntity(EntityListener.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor221.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1056]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:949) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1136) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1126) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1122) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.EntityItem.damageEntity(EntityItem.java:321) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:224) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:1190) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:2453) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:1184) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.createExplosion(CraftWorld.java:1033) ~[patched_1.16.5.jar:git-Purpur-1056]
        at at.pavlov.cannons.CreateExplosion.detonate(CreateExplosion.java:876) ~[?:?]
        at at.pavlov.cannons.projectile.ProjectileManager.detonateProjectile(ProjectileManager.java:116) ~[?:?]
        at at.pavlov.cannons.listener.EntityListener.ProjectileHit(EntityListener.java:75) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1056]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.5.jar:git-Purpur-1056]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1353) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.EntityProjectile.tick(EntityProjectile.java:70) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1542) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1144) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1554) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1403) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Purpur-1056]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1056]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by DerPavlov** [comment]
That is a strange error and it might be an issue with Purpur. To me it looks like the impact location is calculated with the Blockiterator and somehow Purpur messes up the Blockface generation of the vector since the main vector is null. 

When does this error occur?
